### ISSUE TITLE
Init Repository

### ISSUE THREAD

**Issue by adamovittorio** [adamovittorio/lazy-graphql#1]
Configure and install base dependencies and utilities.

Starting with a mono-repo approach we should able to have basic support for development tasks and builds.

- **root**
-- *gateway*
-- *service-one*
-- *service-two*
-- *shared*

### TODOs:

- [x] Lerna
- [x] Typescript (build, watch)
- [x] nvm
- [x] .env
- [x] Eslint (npm, vscode)
- [x] Prettier (npm, vscode)
- [x] Git hooks
- [x] Debugger (npm, docker)
- [x] Document it
